name: CI/CD 구축

# 이벤트를 구독
on: 
  push : # push 이벤트가 발생하면 실행
    branches: # push가 발생한 브랜치가 뭐일때 싱핼할지
      - main

jobs: # 작업의 단위
  myTest: # 실별자 이름 ( 얘만 우리가 정해도 되는 이름)
    runs-on: ubuntu-latest # 사용할 운영 체제 _ubuntu-latest : 최신버전

    # 작업의 가장 작은 단위
    steps: 
      - name: shell console test # 가장 작은 작업 단위의 이름
        run: echo 'my ci/cd' # 작업에서 실행할 쉘 스크립트 내용 echo 출력 audfuddj


